const express = require('express')

const router = express.Router()
const { resultData } = require('../common/utils')

router.get('/menu/getMenuData', (req, res) => {
  res.type('json')
  const ret = {}

  const data = [
    {
      resId: 37,
      resType: 5,
      name: 'Menu4_1',
      fullName: '市场分析',
      icon: null,
      url: '',
      pid: 0,
      level: 1,
      status: 1,
      remark: 'Menu4_1',
      siteId: 5,
      orderNo: 1,
      children: [
        {
          resId: 63,
          resType: 5,
          name: 'Menu4_2',
          fullName: '属性整体分析',
          icon: 'line-chart',
          url: '',
          pid: 37,
          level: 2,
          status: 1,
          remark: 'Menu4_2',
          siteId: 5,
          orderNo: 41,
          children: [
            {
              resId: 67,
              resType: 2,
              name: 'ConsumerDecisionTree',
              fullName: '属性排序分析',
              icon: null,
              url: '/ConsumerDecisionTree',
              pid: 63,
              level: 3,
              status: 1,
              remark: 'ConsumerDecisionTree',
              siteId: 5,
              orderNo: 411,
              children: null,
            },
            {
              resId: 68,
              resType: 2,
              name: 'FullAttributeAnalysis',
              fullName: '属性全景分析',
              icon: null,
              url: '/FullAttributeAnalysis',
              pid: 63,
              level: 3,
              status: 1,
              remark: 'FullAttributeAnalysis',
              siteId: 5,
              orderNo: 412,
              children: null,
            },
            {
              resId: 69,
              resType: 2,
              name: 'TrendProperties',
              fullName: '属性趋势分析',
              icon: null,
              url: '/TrendProperties',
              pid: 63,
              level: 3,
              status: 1,
              remark: 'TrendProperties',
              siteId: 5,
              orderNo: 413,
              children: null,
            },
            {
              resId: 70,
              resType: 2,
              name: 'TrendBrand',
              fullName: '品牌趋势分析',
              icon: null,
              url: '/TrendBrand',
              pid: 63,
              level: 3,
              status: 1,
              remark: 'TrendBrand',
              siteId: 5,
              orderNo: 414,
              children: null,
            },
            {
              resId: 71,
              resType: 2,
              name: 'TrendPriceBand',
              fullName: '价格带趋势分析',
              icon: null,
              url: '/TrendPriceBand',
              pid: 63,
              level: 3,
              status: 1,
              remark: 'TrendPriceBand',
              siteId: 5,
              orderNo: 415,
              children: null,
            },
          ],
        },
        {
          resId: 64,
          resType: 5,
          name: 'Menu4_3',
          fullName: '属性特征画像',
          icon: 'laptop',
          url: '',
          pid: 37,
          level: 2,
          status: 1,
          remark: 'Menu4_3',
          siteId: 5,
          orderNo: 42,
          children: [
            {
              resId: 72,
              resType: 2,
              name: 'MarketImageAnalysis',
              fullName: '市场画像分析',
              icon: null,
              url: '/MarketImageAnalysis',
              pid: 64,
              level: 3,
              status: 1,
              remark: 'MarketImageAnalysis',
              siteId: 5,
              orderNo: 421,
              children: null,
            },
          ],
        },
        {
          resId: 65,
          resType: 5,
          name: 'Menu4_4',
          fullName: '新兴市场定位',
          icon: 'environment-o',
          url: '',
          pid: 37,
          level: 2,
          status: 1,
          remark: 'Menu4_4',
          siteId: 5,
          orderNo: 43,
          children: [
            {
              resId: 73,
              resType: 2,
              name: 'PotentialMarketMining',
              fullName: '市场蓝海挖掘',
              icon: null,
              url: '/PotentialMarketMining',
              pid: 65,
              level: 3,
              status: 1,
              remark: 'PotentialMarketMining',
              siteId: 5,
              orderNo: 431,
              children: null,
            },
            {
              resId: 74,
              resType: 2,
              name: 'PotentialCommodityGenes',
              fullName: '潜力市场基因',
              icon: null,
              url: '/PotentialCommodityGenes',
              pid: 65,
              level: 3,
              status: 1,
              remark: 'PotentialCommodityGenes',
              siteId: 5,
              orderNo: 432,
              children: null,
            },
            {
              resId: 256,
              resType: 2,
              name: 'NewProductIncubator',
              fullName: '新品孵化器',
              icon: null,
              url: '/NewProductIncubator',
              pid: 65,
              level: 3,
              status: 1,
              remark: null,
              siteId: 5,
              orderNo: 788,
              children: null,
            },
          ],
        },
        {
          resId: 66,
          resType: 5,
          name: 'Menu4_5',
          fullName: '竞争品牌分析',
          icon: 'bar-chart',
          url: '',
          pid: 37,
          level: 2,
          status: 1,
          remark: 'Menu4_5',
          siteId: 5,
          orderNo: 44,
          children: [
            {
              resId: 75,
              resType: 2,
              name: 'BrandMarkAnalysis',
              fullName: '品牌对标分析',
              icon: null,
              url: '/BrandMarkAnalysis',
              pid: 66,
              level: 3,
              status: 1,
              remark: 'BrandMarkAnalysis',
              siteId: 5,
              orderNo: 441,
              children: null,
            },
          ],
        },
      ],
    },
    {
      resId: 34,
      resType: 5,
      name: 'Menu1_1',
      fullName: '品类管理',
      icon: null,
      url: '',
      pid: 0,
      level: 1,
      status: 1,
      remark: 'Menu1_1',
      siteId: 5,
      orderNo: 2,
      children: [
        {
          resId: 38,
          resType: 5,
          name: 'Menu1_2',
          fullName: '品类角色看板',
          icon: 'select',
          url: '',
          pid: 34,
          level: 2,
          status: 1,
          remark: 'Menu1_2',
          siteId: 5,
          orderNo: 11,
          children: [
            {
              resId: 40,
              resType: 2,
              name: 'CategoryRole',
              fullName: '品类角色分析',
              icon: null,
              url: '/CategoryRole',
              pid: 38,
              level: 3,
              status: 1,
              remark: 'CategoryRole',
              siteId: 5,
              orderNo: 111,
              children: null,
            },
            {
              resId: 41,
              resType: 2,
              name: 'CategoryCompetitiveness',
              fullName: '品类竞争力分析',
              icon: null,
              url: '/CategoryCompetitiveness',
              pid: 38,
              level: 3,
              status: 1,
              remark: 'CategoryCompetitiveness',
              siteId: 5,
              orderNo: 112,
              children: null,
            },
            {
              resId: 42,
              resType: 2,
              name: 'CategorySalesStructure',
              fullName: '品类销售结构分析',
              icon: null,
              url: '/CategorySalesStructure',
              pid: 38,
              level: 3,
              status: 1,
              remark: 'CategorySalesStructure',
              siteId: 5,
              orderNo: 113,
              children: null,
            },
          ],
        },
        {
          resId: 39,
          resType: 5,
          name: 'Menu1_3',
          fullName: '品类价格看板',
          icon: 'pay-circle-o',
          url: '',
          pid: 34,
          level: 2,
          status: 1,
          remark: 'Menu1_3',
          siteId: 5,
          orderNo: 12,
          children: [
            {
              resId: 43,
              resType: 2,
              name: 'CategoryPriceCharacteristic',
              fullName: '品类价格弹性',
              icon: null,
              url: '/CategoryPriceCharacteristic',
              pid: 39,
              level: 3,
              status: 1,
              remark: 'CategoryPriceCharacteristic',
              siteId: 5,
              orderNo: 121,
              children: null,
            },
            {
              resId: 44,
              resType: 2,
              name: 'CategoryPrice',
              fullName: '品类价格特点',
              icon: null,
              url: '/CategoryPrice',
              pid: 39,
              level: 3,
              status: 1,
              remark: 'CategoryPrice',
              siteId: 5,
              orderNo: 122,
              children: null,
            },
            {
              resId: 240,
              resType: 2,
              name: 'CategoryPriceTrend',
              fullName: '品类价格区间',
              icon: null,
              url: '/CategoryPriceTrend',
              pid: 39,
              level: 3,
              status: 1,
              remark: null,
              siteId: 5,
              orderNo: 332,
              children: null,
            },
          ],
        },
      ],
    },
    {
      resId: 35,
      resType: 5,
      name: 'Menu2_1',
      fullName: '价格管理',
      icon: null,
      url: '',
      pid: 0,
      level: 1,
      status: 1,
      remark: 'Menu2_1',
      siteId: 5,
      orderNo: 3,
      children: [
        {
          resId: 46,
          resType: 5,
          name: 'Menu2_2',
          fullName: '弹性工具',
          icon: 'clock-circle-o',
          url: '',
          pid: 35,
          level: 2,
          status: 1,
          remark: 'Menu2_2',
          siteId: 5,
          orderNo: 21,
          children: [
            {
              resId: 49,
              resType: 2,
              name: 'ElasticTool',
              fullName: '弹性查询器',
              icon: null,
              url: '/ElasticTool',
              pid: 46,
              level: 3,
              status: 1,
              remark: 'ElasticTool',
              siteId: 5,
              orderNo: 211,
              children: null,
            },
          ],
        },
        {
          resId: 47,
          resType: 5,
          name: 'Menu2_3',
          fullName: '品牌挖掘',
          icon: 'tags-o',
          url: '',
          pid: 35,
          level: 2,
          status: 1,
          remark: 'Menu2_3',
          siteId: 5,
          orderNo: 22,
          children: [
            {
              resId: 50,
              resType: 2,
              name: 'PriceBrand',
              fullName: '重点品牌挖掘',
              icon: null,
              url: '/PriceBrand',
              pid: 47,
              level: 3,
              status: 1,
              remark: 'PriceBrand',
              siteId: 5,
              orderNo: 221,
              children: null,
            },
            {
              resId: 51,
              resType: 2,
              name: 'PriceCompetitiveAnalysis',
              fullName: '价格竞争性分析',
              icon: null,
              url: '/PriceCompetitiveAnalysis',
              pid: 47,
              level: 3,
              status: 1,
              remark: 'PriceCompetitiveAnalysis',
              siteId: 5,
              orderNo: 222,
              children: null,
            },
          ],
        },
        {
          resId: 48,
          resType: 5,
          name: 'Menu2_4',
          fullName: '商品盘点',
          icon: 'database',
          url: '',
          pid: 35,
          level: 2,
          status: 1,
          remark: 'Menu2_4',
          siteId: 5,
          orderNo: 23,
          children: [
            {
              resId: 52,
              resType: 2,
              name: 'PriceCommodity',
              fullName: '重点商品定位',
              icon: null,
              url: '/PriceCommodity',
              pid: 48,
              level: 3,
              status: 1,
              remark: 'PriceCommodity',
              siteId: 5,
              orderNo: 231,
              children: null,
            },
            {
              resId: 53,
              resType: 2,
              name: 'PriceSensitivityAnalysis',
              fullName: '价格敏感性分析',
              icon: null,
              url: '/PriceSensitivityAnalysis',
              pid: 48,
              level: 3,
              status: 1,
              remark: 'PriceSensitivityAnalysis',
              siteId: 5,
              orderNo: 232,
              children: null,
            },
          ],
        },
        {
          resId: 253,
          resType: 5,
          name: 'Menu2_5',
          fullName: '价格决策',
          icon: 'solution',
          url: null,
          pid: 35,
          level: 2,
          status: 1,
          remark: null,
          siteId: 5,
          orderNo: 452,
          children: [
            {
              resId: 254,
              resType: 2,
              name: 'WithPriceAdapter',
              fullName: '定价跟价适配',
              icon: null,
              url: '/WithPriceAdapter',
              pid: 253,
              level: 3,
              status: 1,
              remark: '定价跟价适配',
              siteId: 5,
              orderNo: 13,
              children: null,
            },
            {
              resId: 255,
              resType: 2,
              name: 'PriceSimulator',
              fullName: '价格模拟器',
              icon: null,
              url: '/PriceSimulator',
              pid: 253,
              level: 3,
              status: 1,
              remark: '价格模拟器',
              siteId: 5,
              orderNo: 456,
              children: null,
            },
            {
              resId: 263,
              resType: 2,
              name: 'priceExecute',
              fullName: '价格执行',
              icon: null,
              url: 'http://dps.jd.com/',
              pid: 253,
              level: 3,
              status: 1,
              remark: null,
              siteId: 5,
              orderNo: 600,
              children: null,
            },
          ],
        },
      ],
    },
    {
      resId: 36,
      resType: 5,
      name: 'Menu3_1',
      fullName: '促销管理',
      icon: null,
      url: '',
      pid: 0,
      level: 1,
      status: 1,
      remark: 'Menu3_1',
      siteId: 5,
      orderNo: 4,
      children: [
        {
          resId: 54,
          resType: 5,
          name: 'Menu3_2',
          fullName: '基线查询器',
          icon: 'search',
          url: '',
          pid: 36,
          level: 2,
          status: 1,
          remark: 'Menu3_2',
          siteId: 5,
          orderNo: 31,
          children: [
            {
              resId: 76,
              resType: 2,
              name: 'BaselineQuery',
              fullName: '商品基线查询',
              icon: null,
              url: '/BaselineQuery',
              pid: 54,
              level: 3,
              status: 1,
              remark: 'BaselineQuery',
              siteId: 5,
              orderNo: 311,
              children: null,
            },
            {
              resId: 77,
              resType: 2,
              name: 'BaselineTrend',
              fullName: '商品基线趋势',
              icon: null,
              url: '/BaselineTrend',
              pid: 54,
              level: 3,
              status: 1,
              remark: 'BaselineTrend',
              siteId: 5,
              orderNo: 312,
              children: null,
            },
            {
              resId: 78,
              resType: 2,
              name: 'BaselineCategory',
              fullName: '品类基线趋势',
              icon: null,
              url: '/BaselineCategory',
              pid: 54,
              level: 3,
              status: 1,
              remark: 'BaselineCategory',
              siteId: 5,
              orderNo: 313,
              children: null,
            },
          ],
        },
        {
          resId: 55,
          resType: 5,
          name: 'Menu3_3',
          fullName: '促销分析看板',
          icon: 'area-chart',
          url: '',
          pid: 36,
          level: 2,
          status: 1,
          remark: 'Menu3_3',
          siteId: 5,
          orderNo: 32,
          children: [
            {
              resId: 61,
              resType: 2,
              name: 'PromoWhole',
              fullName: '促销整体效果分析',
              icon: null,
              url: '/PromoWhole',
              pid: 55,
              level: 3,
              status: 1,
              remark: 'PromoWhole',
              siteId: 5,
              orderNo: 321,
              children: null,
            },
            {
              resId: 62,
              resType: 2,
              name: 'PromoDetail',
              fullName: '促销明细效果分析',
              icon: null,
              url: '/PromoDetail',
              pid: 55,
              level: 3,
              status: 1,
              remark: 'PromoDetail',
              siteId: 5,
              orderNo: 322,
              children: null,
            },
          ],
        },
        {
          resId: 56,
          resType: 5,
          name: 'Menu3_4',
          fullName: '促销优化设计',
          icon: 'dot-chart',
          url: '',
          pid: 36,
          level: 2,
          status: 1,
          remark: 'Menu3_4',
          siteId: 5,
          orderNo: 33,
          children: [
            {
              resId: 57,
              resType: 2,
              name: 'PromoOptimize',
              fullName: '形式力度优化',
              icon: null,
              url: '/PromoOptimize',
              pid: 56,
              level: 3,
              status: 1,
              remark: 'PromoOptimize',
              siteId: 5,
              orderNo: 331,
              children: null,
            },
            {
              resId: 58,
              resType: 2,
              name: 'PromoThreshold',
              fullName: '促销门槛优化',
              icon: null,
              url: '/PromoThreshold',
              pid: 56,
              level: 3,
              status: 1,
              remark: 'PromoThreshold',
              siteId: 5,
              orderNo: 332,
              children: null,
            },
            {
              resId: 59,
              resType: 2,
              name: 'PromoCoupon',
              fullName: '优惠券门槛优化',
              icon: null,
              url: '/PromoCoupon',
              pid: 56,
              level: 3,
              status: 1,
              remark: 'PromoCoupon',
              siteId: 5,
              orderNo: 333,
              children: null,
            },
            {
              resId: 60,
              resType: 2,
              name: 'PromoPriceOptions',
              fullName: '选品定价优化',
              icon: null,
              url: '/PromoPriceOptions',
              pid: 56,
              level: 3,
              status: 1,
              remark: 'PromoPriceOptions',
              siteId: 5,
              orderNo: 334,
              children: null,
            },
          ],
        },
        {
          resId: 242,
          resType: 5,
          name: 'Menu3_5',
          fullName: '促销效果设计',
          icon: 'dot-chart',
          url: null,
          pid: 36,
          level: 2,
          status: 1,
          remark: 'Menu3_5',
          siteId: 5,
          orderNo: 763,
          children: [
            {
              resId: 243,
              resType: 2,
              name: 'PromoSimulator',
              fullName: '促销效果模拟',
              icon: null,
              url: '/PromoSimulator',
              pid: 242,
              level: 3,
              status: 1,
              remark: 'PromoSimulator',
              siteId: 5,
              orderNo: 994,
              children: null,
            },
          ],
        },
      ],
    },
  ]
  Object.assign(ret, resultData, {
    data,
  })
  res.send(ret)
})

module.exports = router
